name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_test:
    name: asdf plugin unit test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - name: Run bats
        run: scripts/test.bash
